export const FETCH_EXPENSE_CATEGORY_REQUEST = "FETCH_EXPENSE_CATEGORY_REQUEST";
export const FETCH_EXPENSE_CATEGORY_SUCCESS = "FETCH_EXPENSE_CATEGORY_SUCCESS";
export const FETCH_EXPENSE_CATEGORY_FAILURE = "FETCH_EXPENSE_CATEGORY_FAILURE";