export const CHECK_USER_EXIST_REQUEST = 'CHECK_USER_EXIST_REQUEST';
export const CHECK_USER_EXIST_SUCCESS = 'CHECK_USER_EXIST_SUCCESS'; 
export const CHECK_USER_EXIST_FAILURE = 'CHECK_USER_EXIST_FAILURE';